apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ndnq3l5s6-nodejs
  janus-idp.io/tekton: ndnq3l5s6-nodejs
  backstage.io/kubernetes-id: ndnq3l5s6-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ndnq3l5s6-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
